// ============================================================
//  TABOO JR. — THE DECK
//  Each card: [ ANSWER, taboo1, taboo2, taboo3, taboo4, taboo5 ]
//
//  Rules of thumb when adding cards:
//   - The answer should be something an 8-year-old could guess.
//   - The 5 taboo words should be the 5 words you'd MOST want to
//     say. If a taboo word is one you'd never reach for, swap it.
//   - Keep taboo words lowercase, answers UPPERCASE.
//   - No brand names, no anything that needs specific TV/movie
//     knowledge. Run build.py after editing — it checks for
//     duplicates and malformed cards.
// ============================================================

const DECK = [

// ─────────────────────────  ANIMALS  ─────────────────────────
["PENGUIN",       "bird",      "ice",       "black",     "swim",      "waddle"],
["ELEPHANT",      "trunk",     "big",       "gray",      "ears",      "peanut"],
["GIRAFFE",       "neck",      "tall",      "spots",     "zoo",       "leaves"],
["LION",          "king",      "mane",      "roar",      "jungle",    "cat"],
["MONKEY",        "banana",    "tree",      "tail",      "climb",     "zoo"],
["KANGAROO",      "Australia", "hop",       "pouch",     "jump",      "baby"],
["DOLPHIN",       "ocean",     "smart",     "swim",      "jump",      "gray"],
["SHARK",         "teeth",     "ocean",     "fin",       "bite",      "scary"],
["OCTOPUS",       "eight",     "arms",      "ocean",     "ink",       "tentacle"],
["BUTTERFLY",     "wings",     "caterpillar","flower",    "colorful",  "garden"],
["SPIDER",        "web",       "eight",     "legs",      "scary",     "bug"],
["SNAKE",         "slither",   "hiss",      "legs",      "long",      "venom"],
["FROG",          "hop",       "green",     "pond",      "ribbit",    "tadpole"],
["TURTLE",        "shell",     "slow",      "green",     "hide",      "ocean"],
["OWL",           "night",     "hoot",      "bird",      "wise",      "tree"],
["EAGLE",         "bird",      "fly",       "bald",      "America",   "sharp"],
["PARROT",        "talk",      "colorful",  "bird",      "pirate",    "feathers"],
["HAMSTER",       "pet",       "wheel",     "cage",      "small",     "furry"],
["RABBIT",        "hop",       "carrot",    "ears",      "bunny",     "fluffy"],
["SQUIRREL",      "nut",       "tree",      "tail",      "acorn",     "park"],
["HORSE",         "ride",      "saddle",    "gallop",    "neigh",     "farm"],
["COW",           "milk",      "moo",       "farm",      "spots",     "barn"],
["PIG",           "oink",      "mud",       "farm",      "pink",      "bacon"],
["CHICKEN",       "egg",       "cluck",     "farm",      "bird",      "nugget"],
["SHEEP",         "wool",      "baa",       "farm",      "white",     "fluffy"],
["GOAT",          "horns",     "eat",       "farm",      "milk",      "beard"],
["DUCK",          "quack",     "pond",      "water",     "bird",      "feet"],
["BEE",           "honey",     "sting",     "buzz",      "flower",    "yellow"],
["ANT",           "small",     "hill",      "picnic",    "bug",       "colony"],
["WHALE",         "ocean",     "big",       "blue",      "water",     "spout"],
["CRAB",          "claws",     "beach",     "sideways",  "shell",     "ocean"],
["JELLYFISH",     "sting",     "ocean",     "clear",     "float",     "tentacle"],
["STARFISH",      "beach",     "five",      "ocean",     "arms",      "sea"],
["WOLF",          "howl",      "dog",       "moon",      "pack",      "forest"],
["BEAR",          "honey",     "cave",      "hibernate", "growl",     "forest"],
["FOX",           "orange",    "sly",       "tail",      "forest",    "clever"],
["DEER",          "antlers",   "forest",    "run",       "spots",     "hunt"],
["RACCOON",       "trash",     "mask",      "night",     "stripes",   "tail"],
["SKUNK",         "smell",     "spray",     "stripe",    "black",     "stink"],
["MOUSE",         "cheese",    "small",     "squeak",    "trap",      "tail"],
["BEAVER",        "dam",       "teeth",     "wood",      "tail",      "river"],
["TIGER",         "stripes",   "orange",    "cat",       "jungle",    "roar"],
["ZEBRA",         "stripes",   "black",     "white",     "horse",     "Africa"],
["HIPPO",         "water",     "big",       "mouth",     "Africa",    "gray"],
["RHINO",         "horn",      "big",       "gray",      "Africa",    "charge"],
["CHEETAH",       "fast",      "spots",     "run",       "cat",       "Africa"],
["GORILLA",       "ape",       "chest",     "jungle",    "strong",    "banana"],
["PANDA",         "bamboo",    "China",     "black",     "white",     "bear"],
["KOALA",         "Australia", "tree",      "sleep",     "gray",      "leaves"],
["SLOTH",         "slow",      "tree",      "hang",      "lazy",      "jungle"],
["CAMEL",         "hump",      "desert",    "sand",      "ride",      "water"],
["OSTRICH",       "big",       "bird",      "fly",       "fast",      "egg"],
["FLAMINGO",      "pink",      "leg",       "bird",      "stand",     "water"],
["PEACOCK",       "feathers",  "tail",      "blue",      "colorful",  "show"],
["SNAIL",         "slow",      "shell",     "slime",     "garden",    "trail"],
["WORM",          "dirt",      "wiggle",    "fishing",   "long",      "ground"],
["LADYBUG",       "red",       "spots",     "black",     "garden",    "beetle"],
["DRAGONFLY",     "wings",     "pond",      "insect",    "zip",       "skinny"],
["CATERPILLAR",   "butterfly", "crawl",     "leaf",      "cocoon",    "green"],
["LIZARD",        "reptile",   "tail",      "scales",    "sun",       "rock"],
["SEAL",          "ocean",     "clap",      "fish",      "bark",      "flipper"],
["WALRUS",        "tusks",     "ocean",     "big",       "ice",       "whiskers"],
["POLAR BEAR",    "white",     "ice",       "Arctic",    "cold",      "seal"],
["MOOSE",         "antlers",   "big",       "Canada",    "forest",    "deer"],
["BUFFALO",       "big",       "brown",     "herd",      "plains",    "horns"],
["DONKEY",        "farm",      "ears",      "stubborn",  "carry",     "bray"],
["MOLE",          "dig",       "underground","blind",     "tunnel",    "yard"],
["HEDGEHOG",      "spikes",    "small",     "curl",      "prickly",   "ball"],
["OTTER",         "river",     "swim",      "cute",      "float",     "hands"],
["CROCODILE",     "teeth",     "river",     "snap",      "green",     "reptile"],
["TOAD",          "frog",      "bumpy",     "hop",       "warts",     "brown"],
["MOTH",          "light",     "butterfly", "night",     "wings",     "gray"],
["GRASSHOPPER",   "jump",      "green",     "insect",    "lawn",      "legs"],
["CRICKET",       "chirp",     "night",     "bug",       "sound",     "jump"],
["FIREFLY",       "glow",      "night",     "bug",       "light",     "summer"],
["MOSQUITO",      "bite",      "itch",      "buzz",      "blood",     "summer"],
["ROOSTER",       "morning",   "crow",      "farm",      "chicken",   "red"],
["PUPPY",         "dog",       "baby",      "cute",      "bark",      "little"],
["KITTEN",        "cat",       "baby",      "cute",      "meow",      "little"],

// ─────────────────────  FOOD & DRINK  ─────────────────────
["PIZZA",         "cheese",    "slice",     "round",     "pepperoni", "Italian"],
["HAMBURGER",     "bun",       "beef",      "patty",     "grill",     "cheese"],
["SPAGHETTI",     "noodles",   "sauce",     "pasta",     "long",      "meatball"],
["POPCORN",       "movie",     "kernel",    "butter",    "salty",     "bowl"],
["ICE CREAM",     "cone",      "cold",      "scoop",     "sundae",    "sprinkles"],
["PANCAKE",       "syrup",     "breakfast", "flat",      "flip",      "stack"],
["SANDWICH",      "bread",     "lunch",     "slices",    "peanut",    "jelly"],
["CEREAL",        "milk",      "bowl",      "breakfast", "spoon",     "box"],
["COOKIE",        "chocolate", "chip",      "bake",      "jar",       "sweet"],
["CAKE",          "birthday",  "candles",   "frosting",  "slice",     "bake"],
["DONUT",         "hole",      "glaze",     "round",     "sprinkles", "sweet"],
["CUPCAKE",       "frosting",  "small",     "wrapper",   "birthday",  "bake"],
["CANDY",         "sweet",     "Halloween", "sugar",     "wrapper",   "treat"],
["CHOCOLATE",     "brown",     "sweet",     "bar",       "melt",      "candy"],
["LOLLIPOP",      "stick",     "lick",      "candy",     "round",     "sweet"],
["MARSHMALLOW",   "campfire",  "white",     "squishy",   "roast",     "smore"],
["APPLE",         "red",       "fruit",     "tree",      "teacher",   "crunch"],
["BANANA",        "yellow",    "peel",      "monkey",    "fruit",     "curved"],
["ORANGE",        "peel",      "juice",     "round",     "fruit",     "citrus"],
["GRAPES",        "purple",    "bunch",     "small",     "vine",      "raisin"],
["STRAWBERRY",    "red",       "seeds",     "jam",       "sweet",     "shortcake"],
["WATERMELON",    "red",       "seeds",     "summer",    "green",     "slice"],
["PINEAPPLE",     "spiky",     "yellow",    "tropical",  "pizza",     "juice"],
["LEMON",         "yellow",    "sour",      "juice",     "citrus",    "pucker"],
["CARROT",        "orange",    "rabbit",    "vegetable", "crunch",    "ground"],
["BROCCOLI",      "green",     "tree",      "vegetable", "healthy",   "yucky"],
["POTATO",        "fries",     "mash",      "brown",     "vegetable", "chips"],
["CORN",          "yellow",    "cob",       "kernel",    "butter",    "field"],
["TOMATO",        "red",       "ketchup",   "sauce",     "round",     "salad"],
["LETTUCE",       "green",     "salad",     "leaf",      "crunch",    "burger"],
["PEAS",          "green",     "small",     "round",     "pod",       "vegetable"],
["ONION",         "cry",       "layers",    "smell",     "white",     "chop"],
["MUSHROOM",      "fungus",    "forest",    "pizza",     "cap",       "grow"],
["BREAD",         "loaf",      "slice",     "toast",     "bake",      "sandwich"],
["CHEESE",        "yellow",    "milk",      "mouse",     "slice",     "pizza"],
["BUTTER",        "yellow",    "toast",     "spread",    "stick",     "melt"],
["EGG",           "chicken",   "shell",     "yolk",      "crack",     "breakfast"],
["BACON",         "pig",       "crispy",    "breakfast", "strip",     "sizzle"],
["SOUP",          "bowl",      "hot",       "spoon",     "chicken",   "noodle"],
["SALAD",         "lettuce",   "bowl",      "healthy",   "green",     "dressing"],
["TACO",          "shell",     "Mexican",   "fold",      "meat",      "cheese"],
["BURRITO",       "wrap",      "tortilla",  "Mexican",   "beans",     "roll"],
["SUSHI",         "rice",      "fish",      "roll",      "Japan",     "raw"],
["HOT DOG",       "bun",       "mustard",   "ballpark",  "sausage",   "grill"],
["FRENCH FRIES",  "potato",    "ketchup",   "salty",     "fast",      "crispy"],
["PRETZEL",       "salt",      "twist",     "crunchy",   "mall",      "knot"],
["PEANUT BUTTER", "jelly",     "sandwich",  "sticky",    "spread",    "creamy"],
["HONEY",         "bee",       "sticky",    "sweet",     "gold",      "jar"],
["SYRUP",         "pancake",   "sticky",    "maple",     "sweet",     "pour"],
["KETCHUP",       "red",       "tomato",    "fries",     "bottle",    "squeeze"],
["MILK",          "cow",       "white",     "glass",     "cereal",    "drink"],
["JUICE",         "orange",    "drink",     "box",       "fruit",     "squeeze"],
["WATER",         "drink",     "clear",     "thirsty",   "glass",     "wet"],
["LEMONADE",      "stand",     "summer",    "sour",      "sweet",     "pitcher"],
["HOT CHOCOLATE", "cocoa",     "warm",      "winter",    "marshmallow","mug"],
["SODA",          "fizzy",     "bubbles",   "can",       "pop",       "sweet"],
["SMOOTHIE",      "blender",   "fruit",     "straw",     "cold",      "drink"],
["MILKSHAKE",     "straw",     "thick",     "ice",       "cold",      "cup"],
["PIE",           "crust",     "slice",     "apple",     "bake",      "pumpkin"],
["MUFFIN",        "blueberry", "bake",      "breakfast", "cup",       "top"],
["WAFFLE",        "squares",   "syrup",     "breakfast", "iron",      "crispy"],
["TOAST",         "bread",     "butter",    "crispy",    "breakfast", "pop"],
["RICE",          "white",     "grain",     "bowl",      "small",     "chopsticks"],
["NOODLES",       "pasta",     "long",      "slurp",     "soup",      "fork"],
["YOGURT",        "cup",       "spoon",     "creamy",    "fruit",     "healthy"],
["JELLY",         "peanut",    "jar",       "grape",     "spread",    "wiggle"],
["PICKLE",        "cucumber",  "sour",      "jar",       "green",     "crunch"],
["SALT",          "shaker",    "white",     "pepper",    "grain",     "taste"],
["PEPPER",        "salt",      "sneeze",    "black",     "shaker",    "spicy"],
["SUGAR",         "sweet",     "white",     "spoon",     "cube",      "candy"],
["CHIPS",         "bag",       "crunchy",   "potato",    "salty",     "snack"],
["CRACKER",       "cheese",    "crunchy",   "square",    "snack",     "salty"],
["GUM",           "chew",      "bubble",    "stick",     "mint",      "sticky"],
["BIRTHDAY CAKE", "candles",   "wish",      "party",     "frosting",  "sing"],

// ────────────────  AROUND THE HOUSE  ────────────────
["TOOTHBRUSH",    "teeth",     "paste",     "bathroom",  "clean",     "bristles"],
["PILLOW",        "sleep",     "soft",      "bed",       "head",      "fight"],
["BLANKET",       "warm",      "bed",       "cover",     "snuggle",   "cozy"],
["MIRROR",        "reflect",   "look",      "glass",     "bathroom",  "yourself"],
["LAMP",          "light",     "bulb",      "switch",    "table",     "shade"],
["CLOCK",         "time",      "tick",      "hands",     "wall",      "hours"],
["REFRIGERATOR",  "cold",      "food",      "kitchen",   "door",      "magnets"],
["MICROWAVE",     "heat",      "beep",      "kitchen",   "minute",    "popcorn"],
["OVEN",          "bake",      "hot",       "kitchen",   "cook",      "door"],
["SINK",          "water",     "faucet",    "wash",      "dishes",    "drain"],
["BATHTUB",       "water",     "bubbles",   "wash",      "soak",      "bathroom"],
["SHOWER",        "water",     "wash",      "curtain",   "bathroom",  "soap"],
["TOILET",        "flush",     "bathroom",  "seat",      "paper",     "potty"],
["TOWEL",         "dry",       "wet",       "bathroom",  "beach",     "wrap"],
["SOAP",          "wash",      "bubbles",   "hands",     "clean",     "slippery"],
["BROOM",         "sweep",     "floor",     "dust",      "witch",     "handle"],
["VACUUM",        "clean",     "carpet",    "suck",      "loud",      "floor"],
["TRASH CAN",     "garbage",   "throw",     "smelly",    "lid",       "bag"],
["COUCH",         "sit",       "living",    "cushion",   "sofa",      "TV"],
["CHAIR",         "sit",       "legs",      "table",     "back",      "seat"],
["TABLE",         "eat",       "legs",      "flat",      "dinner",    "set"],
["BED",           "sleep",     "pillow",    "blanket",   "night",     "mattress"],
["DOOR",          "open",      "knob",      "close",     "knock",     "enter"],
["WINDOW",        "glass",     "look",      "outside",   "open",      "curtain"],
["STAIRS",        "up",        "down",      "steps",     "climb",     "railing"],
["CARPET",        "floor",     "soft",      "rug",       "vacuum",    "walk"],
["CURTAIN",       "window",    "cloth",     "close",     "hang",      "shower"],
["KEY",           "lock",      "door",      "unlock",    "metal",     "chain"],
["UMBRELLA",      "rain",      "open",      "wet",       "handle",    "cover"],
["FLASHLIGHT",    "dark",      "battery",   "beam",      "camping",   "shine"],
["BATTERY",       "power",     "AA",        "remote",    "charge",    "dead"],
["REMOTE",        "TV",        "buttons",   "channel",   "point",     "lost"],
["SCISSORS",      "cut",       "paper",     "sharp",     "two",       "blades"],
["TAPE",          "sticky",    "roll",      "stick",     "clear",     "wrap"],
["GLUE",          "sticky",    "stick",     "craft",     "bottle",    "paste"],
["HAMMER",        "nail",      "tool",      "hit",       "wood",      "pound"],
["SCREWDRIVER",   "tool",      "twist",     "turn",      "fix",       "flat"],
["LADDER",        "climb",     "steps",     "tall",      "reach",     "rungs"],
["BUCKET",        "water",     "carry",     "handle",    "fill",      "pail"],
["BASKET",        "carry",     "weave",     "picnic",    "handle",    "laundry"],
["CANDLE",        "wax",       "flame",     "birthday",  "light",     "melt"],
["BLENDER",       "smoothie",  "spin",      "loud",      "mix",       "kitchen"],
["TOASTER",       "bread",     "pop",       "hot",       "slot",      "kitchen"],
["DISHWASHER",    "dishes",    "clean",     "kitchen",   "load",      "machine"],
["WASHING MACHINE", "clothes",   "clean",     "spin",      "laundry",   "soap"],
["FAN",           "cool",      "spin",      "blow",      "air",       "hot"],
["PLATE",         "eat",       "round",     "dinner",    "dish",      "food"],
["FORK",          "eat",       "prongs",    "spoon",     "stab",      "utensil"],
["SPOON",         "eat",       "soup",      "scoop",     "fork",      "round"],
["KNIFE",         "cut",       "sharp",     "fork",      "blade",     "slice"],
["CUP",           "drink",     "handle",    "mug",       "water",     "hold"],
["BOWL",          "cereal",    "round",     "soup",      "eat",       "deep"],
["NAPKIN",        "wipe",      "mouth",     "paper",     "dinner",    "messy"],
["STRAW",         "drink",     "suck",      "plastic",   "cup",       "bendy"],

// ─────────────  SCHOOL & LEARNING  ─────────────
["PENCIL",        "write",     "eraser",    "yellow",    "sharpen",   "lead"],
["ERASER",        "mistake",   "pencil",    "rub",       "pink",      "gone"],
["CRAYON",        "color",     "wax",       "draw",      "box",       "paper"],
["MARKER",        "color",     "cap",       "draw",      "smelly",    "ink"],
["BACKPACK",      "school",    "carry",     "straps",    "books",     "shoulders"],
["NOTEBOOK",      "write",     "pages",     "school",    "lines",     "spiral"],
["HOMEWORK",      "school",    "assignment","due",       "boring",    "after"],
["TEACHER",       "school",    "class",     "lesson",    "students",  "board"],
["PRINCIPAL",     "school",    "office",    "boss",      "trouble",   "leader"],
["CHALKBOARD",    "write",     "class",     "erase",     "black",     "teacher"],
["RULER",         "measure",   "inches",    "straight",  "line",      "twelve"],
["GLOBE",         "world",     "spin",      "map",       "round",     "countries"],
["LIBRARY",       "books",     "quiet",     "borrow",    "cards",     "shelves"],
["DESK",          "sit",       "school",    "write",     "table",     "drawer"],
["RECESS",        "play",      "outside",   "school",    "break",     "bell"],
["LUNCHBOX",      "food",      "school",    "carry",     "sandwich",  "pack"],
["REPORT CARD",   "grades",    "school",    "parents",   "letters",   "home"],
["SPELLING",      "letters",   "words",     "test",      "bee",       "correct"],
["MATH",          "numbers",   "add",       "subtract",  "class",     "problems"],
["SCIENCE",       "experiment","lab",       "class",     "discover",  "test"],
["ALPHABET",      "letters",   "ABC",       "twenty",    "sing",      "order"],
["FIELD TRIP",    "bus",       "school",    "museum",    "permission","class"],
["TEST",          "quiz",      "grade",     "study",     "paper",     "questions"],
["PAPER",         "write",     "white",     "sheet",     "tree",      "print"],
["STAPLER",       "staples",   "papers",    "click",     "attach",    "desk"],
["GLUE STICK",    "paste",     "purple",    "craft",     "twist",     "paper"],
["SCHOOL BUS",    "yellow",    "ride",      "stop",      "driver",    "students"],
["ALARM CLOCK",   "wake",      "morning",   "beep",      "snooze",    "time"],

// ──────────────  SPORTS & GAMES  ──────────────
["SOCCER",        "ball",      "kick",      "goal",      "field",     "net"],
["BASKETBALL",    "hoop",      "dribble",   "court",     "shoot",     "orange"],
["BASEBALL",      "bat",       "pitch",     "diamond",   "glove",     "home"],
["FOOTBALL",      "touchdown", "helmet",    "throw",     "field",     "tackle"],
["TENNIS",        "racket",    "net",       "ball",      "court",     "serve"],
["SWIMMING",      "pool",      "water",     "laps",      "stroke",    "goggles"],
["HOCKEY",        "ice",       "puck",      "stick",     "goal",      "skates"],
["GOLF",          "club",      "hole",      "ball",      "course",    "swing"],
["BOWLING",       "pins",      "ball",      "strike",    "lane",      "roll"],
["SKATEBOARD",    "wheels",    "ride",      "trick",     "ramp",      "ollie"],
["BICYCLE",       "pedal",     "wheels",    "ride",      "handlebars","helmet"],
["SCOOTER",       "push",      "wheels",    "ride",      "handle",    "kick"],
["ROLLER SKATES", "wheels",    "feet",      "rink",      "glide",     "four"],
["ICE SKATING",   "rink",      "cold",      "glide",     "blades",    "spin"],
["SKIING",        "snow",      "mountain",  "poles",     "slope",     "downhill"],
["SNOWBOARD",     "mountain",  "ride",      "slope",     "strap",     "winter"],
["SURFING",       "wave",      "ocean",     "board",     "ride",      "beach"],
["JUMP ROPE",     "skip",      "turn",      "recess",    "count",     "swing"],
["HOPSCOTCH",     "chalk",     "squares",   "sidewalk",  "number",    "jump"],
["TAG",           "chase",     "it",        "run",       "touch",     "game"],
["HIDE AND SEEK", "count",     "find",      "ready",     "closet",    "game"],
["TRAMPOLINE",    "jump",      "bounce",    "spring",    "backyard",  "net"],
["MONKEY BARS",   "hang",      "swing",     "playground","hands",     "across"],
["SLIDE",         "playground","down",      "ladder",    "slippery",  "fun"],
["SWING",         "push",      "playground","back",      "forth",     "chains"],
["SEESAW",        "up",        "down",      "playground","balance",   "two"],
["KITE",          "wind",      "fly",       "string",    "sky",       "tail"],
["FRISBEE",       "throw",     "catch",     "disc",      "spin",      "park"],
["PUZZLE",        "pieces",    "fit",       "picture",   "solve",     "table"],
["CHESS",         "board",     "king",      "queen",     "pieces",    "checkmate"],
["CHECKERS",      "board",     "red",       "black",     "jump",      "king"],
["CARDS",         "deck",      "shuffle",   "deal",      "hand",      "game"],
["DICE",          "roll",      "six",       "dots",      "cube",      "game"],
["DOMINO",        "tiles",     "fall",      "dots",      "line",      "tip"],
["MARBLES",       "glass",     "roll",      "small",     "shoot",     "round"],
["YO-YO",         "string",    "up",        "down",      "spin",      "trick"],
["JIGSAW",        "puzzle",    "pieces",    "picture",   "edge",      "fit"],
["RACE",          "run",       "fast",      "finish",    "first",     "start"],
["MEDAL",         "gold",      "win",       "neck",      "prize",     "Olympic"],
["TROPHY",        "win",       "gold",      "cup",       "shelf",     "prize"],
["REFEREE",       "whistle",   "rules",     "game",      "stripes",   "call"],
["COACH",         "team",      "practice",  "teach",     "sideline",  "yell"],
["TEAM",          "group",     "players",   "together",  "win",       "sport"],
["WHISTLE",       "blow",      "sound",     "referee",   "loud",      "coach"],
["HELMET",        "head",      "safety",    "bike",      "hard",      "protect"],
["GOGGLES",       "eyes",      "swim",      "protect",   "strap",     "water"],

// ──────────  PLACES & BUILDINGS  ──────────
["HOSPITAL",      "doctor",    "sick",      "nurse",     "beds",      "ambulance"],
["SCHOOL",        "learn",     "teacher",   "class",     "students",  "bus"],
["ZOO",           "animals",   "cages",     "visit",     "lions",     "tickets"],
["AQUARIUM",      "fish",      "tank",      "water",     "glass",     "sharks"],
["MUSEUM",        "art",       "old",       "visit",     "exhibit",   "quiet"],
["FIRE STATION",  "truck",     "firefighter","pole",      "red",       "emergency"],
["POST OFFICE",   "mail",      "stamps",    "letters",   "packages",  "send"],
["GROCERY STORE", "food",      "cart",      "aisles",    "buy",       "checkout"],
["RESTAURANT",    "eat",       "menu",      "waiter",    "order",     "table"],
["MOVIE THEATER", "screen",    "popcorn",   "seats",     "dark",      "tickets"],
["PARK",          "grass",     "playground","trees",     "outside",   "bench"],
["BEACH",         "sand",      "ocean",     "waves",     "sun",       "towel"],
["FARM",          "animals",   "barn",      "crops",     "tractor",   "field"],
["CASTLE",        "king",      "stone",     "moat",      "tower",     "knight"],
["AIRPORT",       "planes",    "fly",       "gate",      "luggage",   "runway"],
["GAS STATION",   "car",       "fuel",      "pump",      "fill",      "tank"],
["BANK",          "money",     "save",      "account",   "teller",    "vault"],
["CHURCH",        "pray",      "bells",     "Sunday",    "pews",      "steeple"],
["MALL",          "shops",     "stores",    "food",      "buy",       "escalator"],
["PLAYGROUND",    "swings",    "slide",     "kids",      "park",      "recess"],
["CAMPGROUND",    "tent",      "fire",      "outside",   "sleep",     "woods"],
["BARN",          "red",       "farm",      "hay",       "animals",   "loft"],
["TREEHOUSE",     "climb",     "ladder",    "wood",      "hideout",   "backyard"],
["LIGHTHOUSE",    "ocean",     "tall",      "ships",     "beam",      "warn"],
["BRIDGE",        "cross",     "river",     "over",      "road",      "span"],
["TUNNEL",        "through",   "dark",      "mountain",  "underground","road"],
["CAVE",          "dark",      "rocks",     "bats",      "explore",   "underground"],
["ISLAND",        "water",     "surrounded","beach",     "boat",      "palm"],
["DESERT",        "sand",      "hot",       "cactus",    "dry",       "camel"],
["JUNGLE",        "trees",     "vines",     "monkeys",   "hot",       "rainforest"],
["FOREST",        "trees",     "woods",     "green",     "animals",   "hike"],
["MOUNTAIN",      "tall",      "climb",     "peak",      "snow",      "hike"],
["VOLCANO",       "lava",      "erupt",     "mountain",  "hot",       "ash"],
["WATERFALL",     "cliff",     "river",     "loud",      "down",      "mist"],
["HOTEL",         "sleep",     "rooms",     "travel",    "key",       "lobby"],
["GARAGE",        "car",       "park",      "door",      "house",     "tools"],
["BASEMENT",      "downstairs","dark",      "house",     "under",     "storage"],
["ATTIC",         "upstairs",  "dusty",     "boxes",     "roof",      "storage"],

// ─────────  NATURE, WEATHER & OUTDOORS  ─────────
["RAINBOW",       "colors",    "sky",       "arc",       "sun",       "pot"],
["THUNDER",       "loud",      "storm",     "lightning", "boom",      "sky"],
["LIGHTNING",     "flash",     "storm",     "bolt",      "thunder",   "strike"],
["SNOWMAN",       "carrot",    "build",     "scarf",     "melt",      "cold"],
["SNOWFLAKE",     "white",     "fall",      "cold",      "unique",    "winter"],
["ICICLE",        "ice",       "hang",      "drip",      "cold",      "roof"],
["TORNADO",       "wind",      "spin",      "funnel",    "storm",     "damage"],
["HURRICANE",     "storm",     "wind",      "rain",      "eye",       "ocean"],
["FOG",           "cloudy",    "thick",     "morning",   "see",       "gray"],
["CLOUD",         "sky",       "white",     "fluffy",    "rain",      "float"],
["WIND",          "blow",      "air",       "breeze",    "leaves",    "kite"],
["SUNSHINE",      "bright",    "warm",      "sky",       "yellow",    "day"],
["MOON",          "night",     "sky",       "round",     "glow",      "crescent"],
["STARS",         "night",     "sky",       "twinkle",   "wish",      "bright"],
["TREE",          "leaves",    "branches",  "trunk",     "tall",      "wood"],
["FLOWER",        "petals",    "bloom",     "garden",    "smell",     "pretty"],
["GRASS",         "green",     "mow",       "lawn",      "yard",      "blades"],
["LEAF",          "tree",      "green",     "fall",      "rake",      "branch"],
["ROCK",          "hard",      "stone",     "ground",    "throw",     "heavy"],
["SAND",          "beach",     "grains",    "castle",    "desert",    "shovel"],
["RIVER",         "water",     "flow",      "stream",    "bank",      "long"],
["LAKE",          "water",     "swim",      "boat",      "fish",      "shore"],
["OCEAN",         "water",     "waves",     "salty",     "big",       "beach"],
["PUDDLE",        "rain",      "splash",    "water",     "jump",      "small"],
["MUD",           "dirt",      "wet",       "messy",     "brown",     "boots"],
["SEASHELL",      "beach",     "ocean",     "collect",   "hear",      "spiral"],
["CACTUS",        "desert",    "spiky",     "green",     "prickly",   "dry"],
["ACORN",         "oak",       "squirrel",  "nut",       "tree",      "fall"],
["PINECONE",      "tree",      "fall",      "craft",     "brown",     "squirrel"],
["EARTHQUAKE",    "shake",     "ground",    "crack",     "rumble",    "disaster"],
["SUNSET",        "evening",   "orange",    "sky",       "down",      "dark"],
["SUNRISE",       "morning",   "up",        "sky",       "early",     "light"],
["SHADOW",        "dark",      "sun",       "follow",    "shape",     "behind"],
["ECHO",          "sound",     "repeat",    "canyon",    "hear",      "back"],
["CAMPFIRE",      "wood",      "flames",    "marshmallow","warm",      "camping"],
["TENT",          "camping",   "sleep",     "poles",     "zip",       "outside"],
["HIKE",          "walk",      "trail",     "woods",     "boots",     "mountain"],
["FISHING",       "rod",       "hook",      "bait",      "lake",      "catch"],
["BINOCULARS",    "eyes",      "far",       "look",      "two",       "birds"],
["COMPASS",       "north",     "direction", "needle",    "lost",      "point"],
["MAP",           "directions","find",      "roads",     "fold",      "treasure"],
["GARDEN",        "plants",    "grow",      "dirt",      "vegetables","water"],
["SEED",          "plant",     "grow",      "dirt",      "small",     "sprout"],
["ROOTS",         "underground","tree",      "grow",      "dirt",      "bottom"],
["NEST",          "bird",      "eggs",      "twigs",     "tree",      "build"],
["FEATHER",       "bird",      "soft",      "light",     "wing",      "tickle"],
["HONEYCOMB",     "bees",      "hexagon",   "wax",       "hive",      "sticky"],
["ANTHILL",       "ants",      "dirt",      "mound",     "tunnel",    "small"],
["SPIDERWEB",     "sticky",    "silk",      "catch",     "corner",    "bug"],

// ─────────────  BODY & HEALTH  ─────────────
["ELBOW",         "arm",       "bend",      "joint",     "funny",     "point"],
["KNEE",          "leg",       "bend",      "joint",     "scrape",    "cap"],
["SHOULDER",      "arm",       "carry",     "body",      "shrug",     "neck"],
["THUMB",         "finger",    "hand",      "up",        "suck",      "five"],
["TONGUE",        "mouth",     "taste",     "lick",      "stick",     "pink"],
["EYEBROW",       "hair",      "above",     "raise",     "face",      "forehead"],
["EYELASH",       "hair",      "blink",     "wish",      "curl",      "tiny"],
["FRECKLES",      "spots",     "face",      "brown",     "sun",       "nose"],
["DIMPLE",        "cheek",     "smile",     "face",      "hole",      "cute"],
["BELLY BUTTON",  "stomach",   "middle",    "inny",      "outie",     "navel"],
["HEART",         "beat",      "chest",     "pump",      "love",      "blood"],
["BRAIN",         "think",     "head",      "smart",     "skull",     "nerves"],
["LUNGS",         "breathe",   "air",       "chest",     "two",       "oxygen"],
["BONES",         "skeleton",  "hard",      "body",      "break",     "white"],
["MUSCLES",       "strong",    "flex",      "arm",       "lift",      "workout"],
["TEETH",         "mouth",     "brush",     "chew",      "white",     "dentist"],
["HICCUPS",       "breath",    "sound",     "stop",      "water",     "scare"],
["SNEEZE",        "nose",      "achoo",     "cold",      "tissue",    "blow"],
["COUGH",         "throat",    "sick",      "sound",     "cover",     "drops"],
["YAWN",          "tired",     "mouth",     "sleepy",    "open",      "catchy"],
["BANDAGE",       "cut",       "cover",     "sticky",    "boo",       "heal"],
["THERMOMETER",   "fever",     "temperature","sick",      "mouth",     "degrees"],
["MEDICINE",      "sick",      "pills",     "doctor",    "better",    "spoon"],
["VITAMIN",       "healthy",   "chew",      "daily",     "gummy",     "pill"],
["EXERCISE",      "workout",   "healthy",   "sweat",     "gym",       "move"],
["SLEEP",         "bed",       "night",     "tired",     "dream",     "rest"],
["DREAM",         "sleep",     "night",     "imagine",   "nightmare", "wake"],
["SNORE",         "sleep",     "loud",      "nose",      "noise",     "night"],
["TICKLE",        "laugh",     "feather",   "stop",      "armpit",    "giggle"],
["SHIVER",        "cold",      "shake",     "chilly",    "body",      "teeth"],

// ─────────  CLOTHES & THINGS YOU WEAR  ─────────
["MITTENS",       "hands",     "winter",    "warm",      "thumb",     "gloves"],
["SCARF",         "neck",      "winter",    "wrap",      "warm",      "knit"],
["SUNGLASSES",    "eyes",      "shade",     "cool",      "beach",     "bright"],
["BACKWARDS HAT", "cap",       "head",      "turn",      "cool",      "brim"],
["SNEAKERS",      "shoes",     "run",       "laces",     "feet",      "gym"],
["BOOTS",         "feet",      "rain",      "tall",      "mud",       "shoes"],
["FLIP FLOPS",    "feet",      "summer",    "sandals",   "beach",     "toe"],
["SOCKS",         "feet",      "shoes",     "pair",      "lost",      "smelly"],
["PAJAMAS",       "sleep",     "bed",       "night",     "comfy",     "wear"],
["RAINCOAT",      "wet",       "yellow",    "hood",      "dry",       "puddle"],
["SWIMSUIT",      "pool",      "wear",      "beach",     "wet",       "trunks"],
["COSTUME",       "dress",     "Halloween", "pretend",   "wear",      "character"],
["BOW TIE",       "neck",      "fancy",     "suit",      "clip",      "tuxedo"],
["BELT",          "waist",     "pants",     "buckle",    "loops",     "hold"],
["ZIPPER",        "up",        "jacket",    "teeth",     "stuck",     "pull"],
["BUTTON",        "shirt",     "hole",      "sew",       "fasten",    "round"],
["POCKET",        "pants",     "hold",      "hands",     "stuff",     "inside"],
["CROWN",         "king",      "queen",     "head",      "gold",      "jewels"],
["NECKLACE",      "chain",     "jewelry",   "wear",      "pendant",   "beads"],
["BRACELET",      "wrist",     "jewelry",   "arm",       "beads",     "friendship"],
["EARRING",       "jewelry",   "pierce",    "dangle",    "pair",      "lobe"],
["RING",          "finger",    "jewelry",   "gold",      "wedding",   "round"],
["WATCH",         "wrist",     "time",      "arm",       "clock",     "wear"],
["APRON",         "cook",      "kitchen",   "tie",       "messy",     "wear"],
["CAPE",          "hero",      "back",      "fly",       "tie",       "flow"],

// ─────────────  VEHICLES & GOING PLACES  ─────────────
["FIRE TRUCK",    "red",       "siren",     "ladder",    "hose",      "emergency"],
["AMBULANCE",     "hospital",  "siren",     "emergency", "sick",      "lights"],
["POLICE CAR",    "siren",     "officer",   "lights",    "chase",     "badge"],
["TRACTOR",       "farm",      "field",     "plow",      "big",       "wheels"],
["BULLDOZER",     "dig",       "push",      "dirt",      "construction","blade"],
["CRANE",         "lift",      "tall",      "construction","hook",      "heavy"],
["GARBAGE TRUCK", "trash",     "collect",   "smelly",    "cans",      "morning"],
["HELICOPTER",    "blades",    "fly",       "hover",     "spin",      "landing"],
["AIRPLANE",      "fly",       "wings",     "sky",       "pilot",     "airport"],
["ROCKET",        "space",     "launch",    "blast",     "NASA",      "countdown"],
["SUBMARINE",     "underwater","dive",      "ocean",     "periscope", "navy"],
["SAILBOAT",      "wind",      "water",     "mast",      "cloth",     "float"],
["CANOE",         "paddle",    "water",     "narrow",    "river",     "boat"],
["TRAIN",         "tracks",    "cars",      "station",   "whistle",   "engine"],
["SUBWAY",        "underground","train",     "city",      "station",   "tunnel"],
["MOTORCYCLE",    "two",       "wheels",    "loud",      "helmet",    "ride"],
["TAXI",          "yellow",    "ride",      "city",      "driver",    "fare"],
["LIMOUSINE",     "long",      "fancy",     "car",       "driver",    "black"],
["HOT AIR BALLOON", "fly",       "basket",    "float",     "sky",       "burner"],
["SLED",          "snow",      "hill",      "slide",     "down",      "winter"],
["ELEVATOR",      "up",        "down",      "buttons",   "floors",    "doors"],
["ESCALATOR",     "stairs",    "moving",    "mall",      "step",      "up"],
["FERRY",         "boat",      "cars",      "water",     "cross",     "ride"],
["WAGON",         "pull",      "handle",    "red",       "wheels",    "kids"],
["ROLLER COASTER", "ride",      "loop",      "scream",    "park",      "track"],
["FERRIS WHEEL",  "ride",      "round",     "tall",      "fair",      "seats"],
["CAROUSEL",      "horses",    "spin",      "ride",      "music",     "fair"],
["BUMPER CARS",   "crash",     "ride",      "fair",      "electric",  "bang"],

// ────────────  JOBS & PEOPLE  ────────────
["FIREFIGHTER",   "hose",      "truck",     "rescue",    "helmet",    "flames"],
["DOCTOR",        "sick",      "hospital",  "patient",   "medicine",  "checkup"],
["DENTIST",       "teeth",     "drill",     "clean",     "chair",     "floss"],
["VETERINARIAN",  "animals",   "pets",      "sick",      "doctor",    "clinic"],
["ASTRONAUT",     "space",     "suit",      "rocket",    "moon",      "float"],
["PILOT",         "plane",     "fly",       "cockpit",   "wings",     "captain"],
["CHEF",          "cook",      "kitchen",   "hat",       "food",      "restaurant"],
["FARMER",        "crops",     "tractor",   "animals",   "grow",      "barn"],
["ARTIST",        "paint",     "draw",      "canvas",    "create",    "brush"],
["SCIENTIST",     "lab",       "experiment","coat",      "discover",  "research"],
["MAIL CARRIER",  "letters",   "deliver",   "route",     "bag",       "packages"],
["LIFEGUARD",     "pool",      "rescue",    "whistle",   "chair",     "swim"],
["JUDGE",         "court",     "gavel",     "robe",      "decide",    "law"],
["CROSSING GUARD", "street",    "stop",      "kids",      "vest",      "sign"],
["MAGICIAN",      "tricks",    "hat",       "rabbit",    "wand",      "disappear"],
["CLOWN",         "circus",    "nose",      "funny",     "makeup",    "balloons"],
["PIRATE",        "ship",      "treasure",  "parrot",    "eye",       "sail"],
["KNIGHT",        "armor",     "sword",     "castle",    "horse",     "dragon"],
["COWBOY",        "horse",     "hat",       "lasso",     "boots",     "ranch"],
["BABYSITTER",    "kids",      "watch",     "parents",   "night",     "pay"],
["LIBRARIAN",     "books",     "library",   "quiet",     "shelves",   "checkout"],
["JANITOR",       "clean",     "school",    "mop",       "keys",      "cart"],
["MECHANIC",      "car",       "fix",       "garage",    "tools",     "engine"],
["ARCHITECT",     "building",  "design",    "plans",     "draw",      "house"],
["ATHLETE",       "sport",     "train",     "compete",   "strong",    "team"],
["NEIGHBOR",      "next",      "door",      "house",     "borrow",    "street"],
["TWIN",          "two",       "same",      "born",      "sibling",   "identical"],
["GRANDMA",       "grandmother","cookies",   "old",       "mom",       "hug"],

// ────────  HOLIDAYS & CELEBRATIONS  ────────
["HALLOWEEN",     "candy",     "costume",   "October",   "trick",     "pumpkin"],
["PUMPKIN",       "orange",    "carve",     "Halloween", "pie",       "patch"],
["JACK-O-LANTERN", "pumpkin",   "carve",     "candle",    "face",      "glow"],
["THANKSGIVING",  "turkey",    "November",  "family",    "thankful",  "feast"],
["TURKEY",        "Thanksgiving","gobble",    "bird",      "stuffing",  "feast"],
["CHRISTMAS",     "presents",  "tree",      "December",  "Santa",     "snow"],
["SANTA",         "Christmas", "beard",     "chimney",   "presents",  "red"],
["REINDEER",      "Santa",     "sleigh",    "antlers",   "fly",       "nose"],
["SNOW GLOBE",    "shake",     "glass",     "water",     "scene",     "winter"],
["EASTER",        "eggs",      "bunny",     "spring",    "hunt",      "basket"],
["VALENTINE",     "heart",     "love",      "February",  "card",      "candy"],
["BIRTHDAY",      "cake",      "candles",   "presents",  "party",     "age"],
["PRESENT",       "gift",      "wrap",      "bow",       "open",      "surprise"],
["BALLOON",       "air",       "pop",       "party",     "float",     "string"],
["CONFETTI",      "throw",     "party",     "paper",     "colorful",  "celebrate"],
["FIREWORKS",     "sky",       "boom",      "July",      "colors",    "explode"],
["PARADE",        "march",     "floats",    "street",    "band",      "watch"],
["PARTY",         "friends",   "cake",      "games",     "celebrate", "invite"],
["WEDDING",       "marry",     "bride",     "rings",     "cake",      "dress"],
["NEW YEAR",      "midnight",  "January",   "countdown", "resolution","fireworks"],
["TOOTH FAIRY",   "pillow",    "money",     "night",     "wings",     "lost"],
["PIÑATA",        "candy",     "hit",       "stick",     "hang",      "party"],

// ────────────  THINGS YOU DO  ────────────
["SNEAKING",      "quiet",     "tiptoe",    "hide",      "slow",      "caught"],
["WHISPER",       "quiet",     "ear",       "soft",      "secret",    "talk"],
["GIGGLE",        "laugh",     "funny",     "small",     "cover",     "silly"],
["JUGGLE",        "throw",     "balls",     "catch",     "circus",    "three"],
["SOMERSAULT",    "roll",      "flip",      "tumble",    "head",      "over"],
["CARTWHEEL",     "hands",     "spin",      "sideways",  "gymnastics","legs"],
["PIGGYBACK",     "carry",     "ride",      "shoulders", "hold",      "up"],
["HIGH FIVE",     "hand",      "slap",      "celebrate", "palm",      "air"],
["THUMBS UP",     "good",      "hand",      "yes",       "sign",      "approve"],
["HUG",           "arms",      "squeeze",   "love",      "hold",      "warm"],
["WINK",          "eye",       "close",     "one",       "secret",    "blink"],
["SHRUG",         "shoulders", "don't",     "know",      "up",        "unsure"],
["TIPTOE",        "quiet",     "toes",      "sneak",     "walk",      "up"],
["SKIP",          "hop",       "walk",      "happy",     "step",      "along"],
["CRAWL",         "hands",     "knees",     "baby",      "floor",     "slow"],
["SPIN",          "turn",      "round",     "dizzy",     "twirl",     "circle"],
["FLOAT",         "water",     "air",       "top",       "sink",      "drift"],
["DIVE",          "pool",      "head",      "jump",      "water",     "board"],
["SNORKEL",       "tube",      "breathe",   "water",     "mask",      "fish"],
["CAMPING",       "tent",      "outside",   "sleep",     "fire",      "woods"],
["RECYCLE",       "bin",       "reuse",     "plastic",   "green",     "trash"],
["VOTE",          "choose",    "ballot",    "election",  "pick",      "count"],
["SHARE",         "give",      "half",      "friend",    "take",      "turns"],
["APOLOGIZE",     "sorry",     "wrong",     "say",       "forgive",   "mistake"],

// ──────────  IMAGINATION & STORIES  ──────────
["DRAGON",        "fire",      "wings",     "scales",    "knight",    "cave"],
["UNICORN",       "horn",      "horse",     "magic",     "rainbow",   "white"],
["MERMAID",       "tail",      "ocean",     "half",      "fish",      "swim"],
["FAIRY",         "wings",     "magic",     "tiny",      "dust",      "wand"],
["WIZARD",        "magic",     "wand",      "hat",       "spell",     "beard"],
["WITCH",         "broom",     "cauldron",  "hat",       "spell",     "green"],
["GHOST",         "white",     "boo",       "haunted",   "float",     "sheet"],
["VAMPIRE",       "fangs",     "blood",     "night",     "bat",       "cape"],
["ZOMBIE",        "undead",    "brains",    "walk",      "groan",     "scary"],
["MONSTER",       "scary",     "closet",    "big",       "growl",     "under"],
["ROBOT",         "metal",     "beep",      "machine",   "program",   "arms"],
["ALIEN",         "space",     "green",     "UFO",       "planet",    "visitor"],
["SUPERHERO",     "cape",      "powers",    "save",      "fly",       "villain"],
["GENIE",         "lamp",      "wishes",    "three",     "rub",       "magic"],
["TREASURE",      "gold",      "chest",     "buried",    "pirate",    "map"],
["MAGIC WAND",    "wave",      "spell",     "wizard",    "stick",     "sparkle"],
["CRYSTAL BALL",  "future",    "see",       "round",     "fortune",   "glass"],
["GIANT",         "big",       "tall",      "huge",      "beanstalk", "small"],
["TROLL",         "bridge",    "ugly",      "under",     "scary",     "cave"],
["ELF",           "ears",      "small",     "Santa",     "workshop",  "pointy"],

// ──────  SCREENS, MUSIC & MAKING THINGS  ──────
["HEADPHONES",    "ears",      "music",     "listen",    "wear",      "wires"],
["SPEAKER",       "sound",     "loud",      "music",     "volume",    "box"],
["CAMERA",        "photo",     "picture",   "click",     "lens",      "flash"],
["VIDEO GAME",    "controller","play",      "screen",    "level",     "score"],
["CONTROLLER",    "game",      "buttons",   "hold",      "joystick",  "play"],
["KEYBOARD",      "type",      "computer",  "keys",      "letters",   "space"],
["MOUSE PAD",     "computer",  "click",     "flat",      "desk",      "cursor"],
["SCREEN",        "watch",     "display",   "computer",  "bright",    "look"],
["CHARGER",       "plug",      "battery",   "power",     "cord",      "phone"],
["PODCAST",       "listen",    "talk",      "episode",   "audio",     "show"],
["CARTOON",       "animated",  "draw",      "TV",        "funny",     "kids"],
["MOVIE",         "watch",     "screen",    "actors",    "popcorn",   "film"],
["GUITAR",        "strings",   "strum",     "music",     "pick",      "band"],
["PIANO",         "keys",      "black",     "white",     "play",      "music"],
["DRUM",          "beat",      "sticks",    "loud",      "band",      "hit"],
["VIOLIN",        "strings",   "bow",       "chin",      "music",     "orchestra"],
["TRUMPET",       "brass",     "blow",      "loud",      "band",      "valves"],
["FLUTE",         "blow",      "silver",    "band",      "holes",     "high"],
["MICROPHONE",    "sing",      "loud",      "stage",     "voice",     "stand"],
["PAINTBRUSH",    "bristles",  "art",       "canvas",    "stroke",    "color"],
["CLAY",          "mold",      "shape",     "art",       "squish",    "pottery"],
["ORIGAMI",       "paper",     "fold",      "crane",     "Japan",     "art"],
["STICKER",       "peel",      "collect",   "paper",     "back",      "sheet"],
["COMIC BOOK",    "pictures",  "panels",    "superhero", "read",      "bubbles"],

// ────────────  SPACE & SCIENCE  ────────────
["PLANET",        "space",     "orbit",     "round",     "Earth",     "solar"],
["SATURN",        "rings",     "planet",    "space",     "gas",       "orbit"],
["COMET",         "tail",      "space",     "ice",       "streak",    "orbit"],
["METEOR",        "shooting",  "space",     "rock",      "burn",      "wish"],
["TELESCOPE",     "stars",     "look",      "far",       "lens",      "night"],
["MICROSCOPE",    "small",     "look",      "slide",     "lab",       "magnify"],
["MAGNET",        "attract",   "metal",     "stick",     "fridge",    "poles"],
["GRAVITY",       "fall",      "down",      "Earth",     "pull",      "apple"],
["VOLCANO MODEL", "baking",    "soda",      "erupt",     "science",   "fair"],
["FOSSIL",        "dinosaur",  "bones",     "rock",      "old",       "dig"],
["DINOSAUR",      "extinct",   "big",       "Rex",       "fossil",    "roar"],
["SKELETON",      "bones",     "body",      "white",     "Halloween", "skull"],
["BALANCE SCALE", "weigh",     "heavy",     "two",       "sides",     "tip"],
["THERMOSTAT",    "heat",      "cold",      "wall",      "set",       "house"],
["BUBBLE",        "soap",      "float",     "pop",       "round",     "blow"],
["ICE CUBE",      "freeze",    "cold",      "melt",      "tray",      "drink"],
["STEAM",         "hot",       "water",     "boil",      "cloud",     "rise"],
["SHADOW PUPPET", "hands",     "wall",      "light",     "shape",     "dark"],
["SOLAR PANEL",   "sun",       "power",     "roof",      "energy",    "electricity"],
["WINDMILL",      "blades",    "spin",      "power",     "tall",      "farm"],

];
